# coding: utf-8

"""
    ThingsBoard REST API

     ThingsBoard Professional Edition IoT platform REST API documentation.  # noqa: E501

    OpenAPI spec version: 4.1.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EdqsState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'edqs_ready': 'bool',
        'sync_status': 'str',
        'api_mode': 'str'
    }

    attribute_map = {
        'edqs_ready': 'edqsReady',
        'sync_status': 'syncStatus',
        'api_mode': 'apiMode'
    }

    def __init__(self, edqs_ready=None, sync_status=None, api_mode=None):  # noqa: E501
        """EdqsState - a model defined in Swagger"""  # noqa: E501
        self._edqs_ready = None
        self._sync_status = None
        self._api_mode = None
        self.discriminator = None
        if edqs_ready is not None:
            self.edqs_ready = edqs_ready
        if sync_status is not None:
            self.sync_status = sync_status
        if api_mode is not None:
            self.api_mode = api_mode

    @property
    def edqs_ready(self):
        """Gets the edqs_ready of this EdqsState.  # noqa: E501


        :return: The edqs_ready of this EdqsState.  # noqa: E501
        :rtype: object
        """
        return self._edqs_ready

    @edqs_ready.setter
    def edqs_ready(self, edqs_ready):
        """Sets the edqs_ready of this EdqsState.


        :param edqs_ready: The edqs_ready of this EdqsState.  # noqa: E501
        :type: object
        """

        self._edqs_ready = edqs_ready

    @property
    def sync_status(self):
        """Gets the sync_status of this EdqsState.  # noqa: E501


        :return: The sync_status of this EdqsState.  # noqa: E501
        :rtype: object
        """
        return self._sync_status

    @sync_status.setter
    def sync_status(self, sync_status):
        """Sets the sync_status of this EdqsState.


        :param sync_status: The sync_status of this EdqsState.  # noqa: E501
        :type: object
        """

        self._sync_status = sync_status

    @property
    def api_mode(self):
        """Gets the api_mode of this EdqsState.  # noqa: E501


        :return: The api_mode of this EdqsState.  # noqa: E501
        :rtype: object
        """
        return self._api_mode

    @api_mode.setter
    def api_mode(self, api_mode):
        """Sets the api_mode of this EdqsState.


        :param api_mode: The api_mode of this EdqsState.  # noqa: E501
        :type: object
        """

        self._api_mode = api_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EdqsState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdqsState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
