# coding: utf-8

"""
    ThingsBoard REST API

     ThingsBoard open-source IoT platform REST API documentation.  # noqa: E501

    OpenAPI spec version: 4.2.1
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

#  Copyright 2026. ThingsBoard
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import pprint
import re  # noqa: F401

import six

class TbChatRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'system_message': 'str',
        'user_message': 'TbUserMessage',
        'chat_model_config': 'dict'
    }

    attribute_map = {
        'system_message': 'systemMessage',
        'user_message': 'userMessage',
        'chat_model_config': 'chatModelConfig'
    }

    def __init__(self, system_message=None, user_message=None, chat_model_config=None):  # noqa: E501
        """TbChatRequest - a model defined in Swagger"""  # noqa: E501
        self._system_message = None
        self._user_message = None
        self._chat_model_config = None
        self.discriminator = None
        if system_message is not None:
            self.system_message = system_message
        self.user_message = user_message
        self.chat_model_config = chat_model_config

    @property
    def system_message(self):
        """Gets the system_message of this TbChatRequest.  # noqa: E501

        A system-level instruction that frames the user's input, setting the persona, tone, and constraints for the generated response  # noqa: E501

        :return: The system_message of this TbChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._system_message

    @system_message.setter
    def system_message(self, system_message):
        """Sets the system_message of this TbChatRequest.

        A system-level instruction that frames the user's input, setting the persona, tone, and constraints for the generated response  # noqa: E501

        :param system_message: The system_message of this TbChatRequest.  # noqa: E501
        :type: object
        """

        self._system_message = system_message

    @property
    def user_message(self):
        """Gets the user_message of this TbChatRequest.  # noqa: E501

        The actual user prompt that will be answered by the AI model  # noqa: E501

        :return: The user_message of this TbChatRequest.  # noqa: E501
        :rtype: TbUserMessage
        """
        return self._user_message

    @user_message.setter
    def user_message(self, user_message):
        """Sets the user_message of this TbChatRequest.

        The actual user prompt that will be answered by the AI model  # noqa: E501

        :param user_message: The user_message of this TbChatRequest.  # noqa: E501
        :type: TbUserMessage
        """
        if user_message is None:
            raise ValueError("Invalid value for `user_message`, must not be `None`")  # noqa: E501

        self._user_message = user_message

    @property
    def chat_model_config(self):
        """Gets the chat_model_config of this TbChatRequest.  # noqa: E501

        Configuration of the AI chat model that should execute the request  # noqa: E501

        :return: The chat_model_config of this TbChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._chat_model_config

    @chat_model_config.setter
    def chat_model_config(self, chat_model_config):
        """Sets the chat_model_config of this TbChatRequest.

        Configuration of the AI chat model that should execute the request  # noqa: E501

        :param chat_model_config: The chat_model_config of this TbChatRequest.  # noqa: E501
        :type: object
        """
        if chat_model_config is None:
            raise ValueError("Invalid value for `chat_model_config`, must not be `None`")  # noqa: E501

        self._chat_model_config = chat_model_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TbChatRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TbChatRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
