# coding: utf-8

"""
    ThingsBoard REST API

     ThingsBoard Professional Edition IoT platform REST API documentation.  # noqa: E501

    OpenAPI spec version: 3.5.0PE
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from tb_rest_client.models.models_pe.users_filter import UsersFilter  # noqa: F401,E501

class UserRoleFilter(UsersFilter):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'roles_ids': 'list[str]'
    }
    if hasattr(UsersFilter, "swagger_types"):
        swagger_types.update(UsersFilter.swagger_types)

    attribute_map = {
        'roles_ids': 'rolesIds'
    }
    if hasattr(UsersFilter, "attribute_map"):
        attribute_map.update(UsersFilter.attribute_map)

    def __init__(self, roles_ids=None, *args, **kwargs):  # noqa: E501
        """UserRoleFilter - a model defined in Swagger"""  # noqa: E501
        self._roles_ids = None
        self.discriminator = None
        if roles_ids is not None:
            self.roles_ids = roles_ids
        UsersFilter.__init__(self, *args, **kwargs)

    @property
    def roles_ids(self):
        """Gets the roles_ids of this UserRoleFilter.  # noqa: E501


        :return: The roles_ids of this UserRoleFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._roles_ids

    @roles_ids.setter
    def roles_ids(self, roles_ids):
        """Sets the roles_ids of this UserRoleFilter.


        :param roles_ids: The roles_ids of this UserRoleFilter.  # noqa: E501
        :type: list[str]
        """

        self._roles_ids = roles_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserRoleFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserRoleFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
